version: "3.8"

services:
  flask:
    build:
      context: .
    platform: linux/amd64
    container_name: flask_template
    restart: always
    expose:
      - 5000
  nginx:
    build:
      context: ./nginx
    platform: linux/amd64
    container_name: nginx
    restart: always
    ports:
      - "80:80"